config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :users, only: [:new, :create, :show] do
  	resources :ideas
  end

  get '/login', to: "sessions#new"

  post '/login', to: "sessions#create"

  delete '/logout', to: "sessions#destroy"

  namespace :admin do
  	resources :categories, only: [:index, :new, :create, :destroy]
    resources :images, only: [:new, :index, :create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :ideas

	validates :name, presence: true,
					 uniqueness: true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :idea_images
  has_many :images, through: :idea_images

  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true
  validates :category_id, presence: true
end

app/models/idea_image.rb
class IdeaImage < ApplicationRecord
  belongs_to :idea
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
	has_many :idea_images
	has_many :ideas, through: :idea_images

	has_attached_file :image, styles: { standard: "300x300>" }
	validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg"]
	validates :name, presence: true
	validates :image, attachment_presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :ideas

  has_secure_password
  
  validates :username, presence: true,
  					   uniqueness: true
  validates :email, presence: true,
  					uniqueness: true
  validates :password, presence: true

  enum role: ["default", "admin"]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_action :redirect?
	before_action :require_admin

	def require_admin
		render file: '/public/404' unless current_admin?
	end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to admin_categories_path
		else
			render :new
		end
	end

	def destroy
		@category = Category.find(params[:id])
		if @category.destroy
			redirect_to admin_categories_path
		else
			redirect_to admin_categories_path
		end
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

	def index
		@images = Image.all
	end

	def new
		@image = Image.new
	end

	def create
		@image = Image.new(image_params)
		if @image.save
			redirect_to admin_images_path
		else
			render :new
		end
	end

	def destroy
		@image = Image.find(params[:id])
		if @image.destroy
			redirect_to admin_images_path
		else
			redirect_to admin_images_path
		end
	end

	private

	def image_params
		params.require(:image).permit(:name, :image)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :current_admin?

  def current_user
  	@user = User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
  	current_user && current_user.admin?
  end

  def redirect?
	redirect_to root_path unless current_user
  end

end

app/controllers/base_controller.rb
class BaseController < ApplicationController
	before_action :redirect?

	def logged_in?
		render file: '/public/404' unless current_user
	end

	def not_authorized
		current_user.id != params[:id].to_i 
	end

	def authorized
		render file: '/public/404' unless (current_user.id == params[:user_id].to_i)
	end

	def render_404
		render file: '/public/404'
	end

end

app/controllers/ideas_controller.rb
class IdeasController < BaseController
	before_action :logged_in?
	before_action :authorized

	def index
		@ideas = Idea.where(user_id: params[:user_id])
	end

	def new
		@user = User.find(params[:user_id])
		@idea = current_user.ideas.new
		@categories = Category.all
		@images = Image.all
	end

	def create
		idea = current_user.ideas.new(idea_params)
		if idea.save
			redirect_to user_idea_path(current_user, idea)
		else
			render :new
		end
	end

	def show
  		@idea = Idea.find(params[:id])
		@category = @idea.category
  		@user = User.find(params[:user_id])
	end

	def edit
		@idea = Idea.find(params[:id])
		@categories = Category.all
		@images = Image.all
	end

	def update
		idea = current_user.ideas.find(params[:id])
		if idea.update(idea_params)
			redirect_to user_idea_path(current_user, idea)
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:user_id])
		@idea = Idea.find(params[:id])
		@idea.destroy

		redirect_to user_ideas_path(@user)
	end

	private

	def idea_params
		params.require(:idea).permit(:title, :body, :category_id, image_ids: [])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear

    flash.notice = "Logged Out"

    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < BaseController
  skip_before_action :redirect?, except: :show
  before_action :logged_in?, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    user = current_user
    if not_authorized
      render_404
    else
      @user = user
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Categories</title>
</head>
<body>
	<ul>
	<% @categories.each do |category| %>
		<li class="category_<%= category.id %>">
		<%= category.name %>: 
		<%= link_to "Delete", admin_category_path(category), method: :delete %>	
		</li>
	<% end %>
	</ul>
</body>
</html>

app/views/admin/categories/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>New Category</title>
</head>
<body>
	<%= form_for [:admin, @category] do |f| %>
		<%= f.label :name, "Name" %>
		<%= f.text_field :name %>

		<%= f.submit %>
	<% end %>				
</body>
</html>

app/views/admin/images/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>All Images</title>
</head>
<body>
	<ul>
	<% @images.each do |img| %>
		<li class="image_<%= img.id %>">
		<%= image_tag img.image.url(:standard) %>
		<%= img.name %>
		<%= link_to "Delete", admin_image_path(img), method: :delete %>	
		</li>
	<% end %>
	</ul>
</body>
</html>

app/views/admin/images/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>New Image</title>
</head>
<body>
	<%= form_for [:admin, @image] do |f| %>
			<%= f.label :name, "Name" %>
			<%= f.text_field :name %>

			<%= f.label :image, "Attach an Image" %>
			<%= f.file_field :image %>

			<%= f.submit "Create Image" %>
	<% end %>
</body>
</html>

app/views/ideas/_form.html.erb
<%= form_for [current_user, @idea] do |f| %>
	<%= f.label :title, "Title" %>
	<%= f.text_field :title %>

	<%= f.label :body, "Description" %>
	<%= f.text_area :body %>

	<%= f.label :category_id, "Category" %>
	<%= f.collection_select :category_id, @categories, :id, :name %>

	<%= f.collection_check_boxes :image_ids, @images, :id, :name do |b| %>
		<%= b.check_box %>
		<%= b.label %>
	<% end %>

	<%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Edit Idea</title>
</head>
<body>
	<%= render partial: "form" %>
</body>
</html>

app/views/ideas/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Ideas</title>
</head>
<body>
	<h1>All ideas for <%= current_user.username %></h1>
	<table>
		<thead>
			<tr>
				<th>Idea</th>
				<th>Description</th>
			</tr>
		</thead>
		<tbody>
			<% @ideas.each do |idea| %>
			<tr>
				<td><%=link_to idea.title, user_idea_path(current_user, idea) %></td>
				<td><%= idea.body %></td>	
			</tr>
			<% end %>
		</tbody>
	</table>
</body>
</html>

app/views/ideas/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Create a New Idea</title>
</head>
<body>
	<%= render partial: "form" %>
</body>
</html>

app/views/ideas/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Idea</title>
</head>
<body>
	<h1><%= @idea.title %></h1>
	<% @idea.images.each do |img| %>
		<p><%= image_tag img.image.url(:standard) %></p>
	<% end %>
	<p><%= @idea.body %></p>
	<p><%= @category.name %></p>
	<p><%= link_to "Edit", edit_user_idea_path(current_user, @idea) %></p>
	<p><%= link_to "Delete", user_idea_path(current_user, @idea), method: :delete %></p>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>



  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Idea Box</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <% if current_user %>
            <a class="nav-item nav-link active" href="<%= user_path(current_user) %>"><%= current_user.username %>'s Idea Box<span class="sr-only">(current)</span></a>
          <% end %>
        </div>
        <div class="navebar-nav">
          <% if current_user %>
            <li class="nav-link mr-auto">
              <%= link_to "Log Out", logout_path, method: :delete %>
            </li>
          <% end %> 
        </div>
      </div>
    </nav>

    <div class="jumbotron vertical-center">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 text-center">
            <p><%= flash.notice %></p>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New User</title>
  </head>
  <body>
    <h1>Sign up for Idea Box:</h1>
    <%= form_for @user do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Create Account" %>
    <% end %>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= @user.username %>'s IdeaBox</title>
  </head>
  <body>
    <h1><%= @user.username %>'s IdeaBox</h1>
	    <p><%= link_to "Create an Idea", new_user_idea_path(@user) %></p>
	    <p><%= link_to "See All Ideas", user_ideas_path(@user) %></p>
    <% if current_admin? %>
	    <h3>Admin Options</h3>
	    <p><%= link_to "Create New Category", new_admin_category_path %></p>
	    <p><%= link_to "Delete a Category", admin_categories_path %></p>
      <p><%= link_to "Add a New Image", new_admin_image_path %></p>
      <p><%= link_to "See All Images", admin_images_path %></p>
    <% end %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Idea Box</h1>
<br>
<p><%= link_to "Sign Up", new_user_path %></p>
<p><%= link_to "Log In", login_path %></p>